### ISSUE TITLE
Crush displays help message

### ISSUE THREAD

**Issue by kovtunos** [dockerizedrupal/crush#3]
Crush (Version: 1.1.3) always displays help message before command output.
Commands work properly.

```
which drush
/usr/local/bin/drush
```

Here's the versions of images I use.

```
dockerizedrupal/vhost:1.1.7       
dockerizedrupal/apache-2.4:1.2.0  
dockerizedrupal/php-5.4:1.2.0     
dockerizedrupal/memcachephp:1.1.1 
dockerizedrupal/phpmyadmin:1.1.1  
dockerizedrupal/adminer:1.1.1     
dockerizedrupal/mysql:1.2.1       
dockerizedrupal/mailcatcher:1.1.0 
dockerizedrupal/memcached:1.1.0

docker-compose 1.5.2
drupal-compose 1.2.1
```

**Comment by viljaste** [comment]
Hi kovtunos,

Thank you for reporting this, I'll take a look why this is happening in the latest version.

I think that version 1.1.2 should work correctly though, so please use 1.1.2 instead of 1.1.3 in the mean time.

```
TMP="$(mktemp -d)" \
  && git clone https://github.com/dockerizedrupal/crush.git "${TMP}" \
  && cd "${TMP}" \
  && git checkout 1.1.2 \
  && sudo cp "${TMP}/crush.sh" /usr/local/bin/crush \
  && sudo chmod +x /usr/local/bin/crush \
  && cd -
```

**Comment by kovtunos** [comment]
Version 1.1.2 works correctly. Thanks.
Your excellent solution helps to simplify my daily work.

**Comment by viljaste** [comment]
It's awesome, that these tools are helping you to simplify your daily work!

I've released an updated version (1.1.4) of Crush, which should work now as expected.

If you have any day to day questions or other issues with the setup, feel free to join our IRC channel (#dockerizedrupal) at freenode for help :).

http://webchat.freenode.net/?channels=dockerizedrupal

**Comment by kovtunos** [comment]
Thanks. It works.

**Comment by Vacilando** [comment]
Since a few days, whatever drush command I issue I get "crush: Waiting for PHP service to come up..."

I'd like to update to the latest Crush in hope that will fix it -- but how can I update it?

**Comment by kovtunos** [comment]
> I'd like to update to the latest Crush in hope that will fix it -- but how can I update it?

```
TMP="$(mktemp -d)" \
  && git clone https://github.com/dockerizedrupal/crush.git "${TMP}" \
  && cd "${TMP}" \
  && git checkout 1.1.4 \
  && sudo cp "${TMP}/crush.sh" /usr/local/bin/crush \
  && sudo chmod +x /usr/local/bin/crush
```

**Comment by viljaste** [comment]
The group of commands that @kovtunos has given is currently the correct way to update Crush.

**Comment by Vacilando** [comment]
Thank you, @kovtunos & @viljaste. The Crush update worked this way. 
However, it did not help me with my Drush issue, so I opened a ticket #4.
