### ISSUE TITLE
drush not working, message "PHP container could not be found"

### ISSUE THREAD

**Issue by Vacilando** [dockerizedrupal/crush#4]
Since a few days I am unable to use drush. The system always thinks it has to start containers - even though I had started them before - and then does nothing.

vagrant@dev:/var/www/onet.dev$ drush status
crush: PHP container could not be found. Would you like to start the containers? [Y/n]: Y
Starting onetdev_mysql-data_1
onetdev_memcached_1 is up-to-date
onetdev_mailcatcher_1 is up-to-date
onetdev_mysql_1 is up-to-date
onetdev_adminer_1 is up-to-date
onetdev_phpmyadmin_1 is up-to-date
onetdev_memcachephp_1 is up-to-date
Starting onetdev_apache-data_1
onetdev_php_1 is up-to-date
onetdev_apache_1 is up-to-date
crush: Waiting for PHP service to come up...
vagrant@dev:/var/www/onet.dev$

Any ideas?

**Comment by viljaste** [comment]
Vacilando, have you already resolved it by now?

Does the project itself work over the HTTP?

**Comment by Vacilando** [comment]
Jurgen, no, it hasn't been resolved :-(

The project itself does indeed work. It's just that d/crush never finds the PHP container and wants to (unsuccessfully) start it up.

**Comment by viljaste** [comment]
Is it possible for you to provide the docker-compose.yml file for that particular project?

Of course don't forget to sanitize the sensitive data beforehand.

And to be sure that you are running the latest version of Crush, please provide the output of the following command:

```
crush --version
```

**Comment by Vacilando** [comment]
I'll get you the info asap.

( BTW, one of the solutions I thought about was upgrading the dockerizedrupal setup. See my question at https://dockerizedrupal.com/getting-started/installation/windows/start-the-guest-virtual-machine-with-vagrant#comment-2533664227 )

**Comment by Vacilando** [comment]
vagrant@dev:~$ crush --version
Version: 1.1.4

docker-compose.yml is attached (added ".txt" to be able to upload it).
It's simply the one I had generated using drupal-compose.

[docker-compose.yml.txt](https://github.com/dockerizedrupal/crush/files/166256/docker-compose.yml.txt)

**Comment by viljaste** [comment]
Tomáš, your Docker Compose file looks OK.

There seems to be an issue with your Vagrant environment as it seems that Crush is not able to interpret your environment variables properly.

I've added some better debugging capabilities to Crush which can help us to better understand what exactly is happening inside Crush while you are using it.

Please update Crush to version 1.1.5 to be able to use this feature as follows:

```
TMP="$(mktemp -d)" \
  && git clone https://github.com/dockerizedrupal/crush.git "${TMP}" \
  && cd "${TMP}" \
  && git checkout 1.1.5 \
  && sudo cp "${TMP}/crush.sh" /usr/local/bin/crush \
  && sudo chmod +x /usr/local/bin/crush \
  && cd - 
```

To enable the debug mode, add `--debug` flag to your Crush command as follows:

```
drush status --debug
```

Please provide the command output alongside with your next reply.

Regarding the question on how to update the Dockerized Drupal virtual machine, I'm currently putting together a documentation for that. I'll update you as soon as I've completed it.

**Comment by Vacilando** [comment]
Done the update, did again docker-compose up, then the drush with --debug option:

vagrant@dev:/var/www/onet.dev$ docker-compose up -d  
Starting onetdev_mysql-data_1
onetdev_memcached_1 is up-to-date
onetdev_mailcatcher_1 is up-to-date
onetdev_mysql_1 is up-to-date
onetdev_adminer_1 is up-to-date
onetdev_phpmyadmin_1 is up-to-date
onetdev_memcachephp_1 is up-to-date
Starting onetdev_apache-data_1
onetdev_php_1 is up-to-date
onetdev_apache_1 is up-to-date
vagrant@dev:/var/www/onet.dev$ drush status --debug
[ DEBUG ] crush: Crush version: 1.1.5
[ DEBUG ] crush: Working directory: /var/www/onet.dev
[ DEBUG ] crush: Docker version: 1.9.1, build a34a1d5
[ DEBUG ] crush: Docker Compose version: 1.5.2, build 7240ff3
[ DEBUG ] crush: Docker Compose file: docker-compose.yml
[ DEBUG ] crush: Project root: /var/www/onet.dev
[ DEBUG ] crush: PHP container name:
crush: PHP container could not be found. Would you like to start the containers? [Y/n]:
...

**Comment by Vacilando** [comment]
Hi,

On another PC I installed 0.4.9 from scratch -- all went fine, but when finished, I found out to my dismay that drush does not work :-(
It is impossible to develop efficiently without drush so I went for a radical solution, reinstalled vagrant and everything from scratch, but now on version 0.4.8 (which worked on another Win10 PC). (Meaning I now use Crush version 1.1.4.)

Alas, drush does not work.

Here's what I observe:

vagrant@dev:/var/www/d7.dev$ docker-compose up -d
Starting d7dev_mysql-data_1
d7dev_memcached_1 is up-to-date
d7dev_mailcatcher_1 is up-to-date
d7dev_mysql_1 is up-to-date
d7dev_adminer_1 is up-to-date
d7dev_phpmyadmin_1 is up-to-date
d7dev_memcachephp_1 is up-to-date
Starting d7dev_apache-data_1
d7dev_php_1 is up-to-date
d7dev_apache_1 is up-to-date
vagrant@dev:/var/www/d7.dev$ drush dl devel -y
crush: PHP container is not running. Would you like to start the containers? [Y/n]: Y
Starting d7dev_mysql-data_1
d7dev_memcached_1 is up-to-date
d7dev_mailcatcher_1 is up-to-date
d7dev_mysql_1 is up-to-date
d7dev_adminer_1 is up-to-date
d7dev_phpmyadmin_1 is up-to-date
d7dev_memcachephp_1 is up-to-date
Starting d7dev_apache-data_1
d7dev_php_1 is up-to-date
d7dev_apache_1 is up-to-date
crush: Waiting for PHP service to come up...
json: cannot unmarshal array into Go value of type types.ContainerJSON
Error response from daemon: No such container: d7dev_php_

One thing:
- Container d7dev_php_1 is running.
- The system cannot find PHP container and gives up and says "No such container: d7dev_php_".
  Note there is no number at the end of the container that it searches for!

Any idea why the last number cannot be found? Can I force (hardcode) it even if all fails? I am messing with this for a few days on and off again, most frustrating.
Any help welcome!

**Comment by Vacilando** [comment]
Upgrade to crush version 2.0.0 solves the issue.
