### ISSUE TITLE
Crush does not play well with drush.complete.sh and the Ubuntu ttys

### ISSUE THREAD

**Issue by frederickjh** [dockerizedrupal/crush#6]
Hi!
I am not using Dockerize Drupal regularly right now. I installed it the other day to "kick the tires". 

Today I switched to a tty (Ctrl+Alt+F1  through F6 there are 6 ttys on Ubuntu 14.04 by default. Ctrl+Alt+F7 to get back to the GUI) In fish (friendly interactive shell) drush completion did not work. I then switched to bash in the tty and found drush completion did not work there either and it was also displaying a message that __drush_ps1 was not found. This is a function in the drush.complete.sh file that displays the site you are working on in the prompt. 

In Drush there is a **use** command. This is the same as the MySQL use command. In Drush you can say `drush use @mysite`. Then any commands that you run with drush will be run against that site alias. The __drush_ps1 allows you to add the site you are working to to your prompt, otherwise there is no indication as to which site a command will be run against.

The drush completion works fine in the Gnome terminals in Unity on Ubuntu with the drush link to crush in place but in the ttys drush completion does not work. Removing the link allows drush completion to work again. Since I am not using Dockerize Drupal regularly I have removed the link.

Let me know if there is any information that I can provide to help troubleshoot this.

God Bless!
Frederick

**Comment by viljaste** [comment]
Closing this as this project is unfortunately not active anymore.
