### ISSUE TITLE
Does Drupal Console work in Dockerized Drupal environment?

### ISSUE THREAD

**Issue by kovtunos** [dockerizedrupal/crush#8]
I don't know where exactly to put this issue. I'm looking a way [Drupal Console](https://drupalconsole.com/) can be started in Dockerized Drupal environment.

**Comment by viljaste** [comment]
Drupal Console is actually already installed into PHP image. If you enter the PHP container with the following command:

`docker exec -it myproject_php_1 bash -l`

you can move to your project directory like so:

`cd /apache/data`

and use `drupal` command to interact with Drupal.

**Comment by kovtunos** [comment]
All inclusive.
Thank you for the great environment for Drupal developers.

**Comment by Niklan** [comment]
Hi, folks.

I tried to use Drupal Console, all works fine, but only one thing confusing me. All files created by drupal console in container has root owner and group. How can i change it. In host.yml all values is 1000 as my `echo $UID`

**Comment by viljaste** [comment]
Hi Niklan,

To have the right permissions generated by Drupal Console for your project inside the PHP container you can simply switch to user called `container` which have the same user and group ID as your host user by executing the following command:

`su container`

**Comment by Niklan** [comment]
Hi viljaste,

I do that and get this error:

```
container@php:/apache/data$ drupal check
/usr/bin/env: php: No such file or directory
```

UPD I use PHP 7.0 container

**Comment by viljaste** [comment]
Sorry, the right command is following:

`su -l container`

**Comment by Niklan** [comment]
@viljaste brilliant, thank you.
